//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClassLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedClassLibrary.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to authenticate.
        /// </summary>
        public static string Autentication_Error {
            get {
                return ResourceManager.GetString("Autentication_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Debugging_Message {
            get {
                return ResourceManager.GetString("Debugging_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Debugging_Source {
            get {
                return ResourceManager.GetString("Debugging_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace.
        /// </summary>
        public static string Debugging_StackTrace {
            get {
                return ResourceManager.GetString("Debugging_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found.
        /// </summary>
        public static string Error_ErrorFound {
            get {
                return ResourceManager.GetString("Error_ErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_ErrorLowercase {
            get {
                return ResourceManager.GetString("Error_ErrorLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error_ErrorUppercase {
            get {
                return ResourceManager.GetString("Error_ErrorUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel sheet does not have the required format.
        /// </summary>
        public static string Error_ExcelSheetFormatError {
            get {
                return ResourceManager.GetString("Error_ExcelSheetFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id.
        /// </summary>
        public static string Error_InvalidId {
            get {
                return ResourceManager.GetString("Error_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string Error_ItemNotFound {
            get {
                return ResourceManager.GetString("Error_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be null.
        /// </summary>
        public static string Error_NullValue {
            get {
                return ResourceManager.GetString("Error_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the sheet header.
        /// </summary>
        public static string Error_SheetHeaderError {
            get {
                return ResourceManager.GetString("Error_SheetHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has stopped.
        /// </summary>
        public static string Error_ThreadStopped {
            get {
                return ResourceManager.GetString("Error_ThreadStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the data entered is correct and try again.
        /// </summary>
        public static string Error_ValidateInput {
            get {
                return ResourceManager.GetString("Error_ValidateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No_Camelcase {
            get {
                return ResourceManager.GetString("No_Camelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No_Lowercase {
            get {
                return ResourceManager.GetString("No_Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No_Uppercase {
            get {
                return ResourceManager.GetString("No_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Results_Created {
            get {
                return ResourceManager.GetString("Results_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Results_Deleted {
            get {
                return ResourceManager.GetString("Results_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Results_Failed {
            get {
                return ResourceManager.GetString("Results_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Results_Modified {
            get {
                return ResourceManager.GetString("Results_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched.
        /// </summary>
        public static string Results_Searched {
            get {
                return ResourceManager.GetString("Results_Searched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Results_Success {
            get {
                return ResourceManager.GetString("Results_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Results_Updated {
            get {
                return ResourceManager.GetString("Results_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Results_Warning {
            get {
                return ResourceManager.GetString("Results_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Inactive.
        /// </summary>
        public static string Search_HideInactive {
            get {
                return ResourceManager.GetString("Search_HideInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Title_ResultCamelcase {
            get {
                return ResourceManager.GetString("Title_ResultCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT.
        /// </summary>
        public static string Title_ResultUppercase {
            get {
                return ResourceManager.GetString("Title_ResultUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Validation_ActionCamelcase {
            get {
                return ResourceManager.GetString("Validation_ActionCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to do.
        /// </summary>
        public static string Validation_ActionToDoCamelcase {
            get {
                return ResourceManager.GetString("Validation_ActionToDoCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION TO DO.
        /// </summary>
        public static string Validation_ActionToDoUppercase {
            get {
                return ResourceManager.GetString("Validation_ActionToDoUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION.
        /// </summary>
        public static string Validation_ActionUppercase {
            get {
                return ResourceManager.GetString("Validation_ActionUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Required.
        /// </summary>
        public static string Validation_AdditionalRequiredCamelcase {
            get {
                return ResourceManager.GetString("Validation_AdditionalRequiredCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITIONAL REQUIRED.
        /// </summary>
        public static string Validation_AdditionalRequiredUppercase {
            get {
                return ResourceManager.GetString("Validation_AdditionalRequiredUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informative.
        /// </summary>
        public static string Validation_InformationCamelcase {
            get {
                return ResourceManager.GetString("Validation_InformationCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATIVE.
        /// </summary>
        public static string Validation_InformationUppercase {
            get {
                return ResourceManager.GetString("Validation_InformationUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string Validation_MandatoryCamelcase {
            get {
                return ResourceManager.GetString("Validation_MandatoryCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANDATORY.
        /// </summary>
        public static string Validation_MandatoryUppercase {
            get {
                return ResourceManager.GetString("Validation_MandatoryUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Validation_OptionalCamelcase {
            get {
                return ResourceManager.GetString("Validation_OptionalCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONAL.
        /// </summary>
        public static string Validation_OptionalUppercase {
            get {
                return ResourceManager.GetString("Validation_OptionalUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Validation_OptionCamelcase {
            get {
                return ResourceManager.GetString("Validation_OptionCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTION.
        /// </summary>
        public static string Validation_OptionUppercase {
            get {
                return ResourceManager.GetString("Validation_OptionUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Validation_SelectCamelcase {
            get {
                return ResourceManager.GetString("Validation_SelectCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTION.
        /// </summary>
        public static string Validation_SelectUppercase {
            get {
                return ResourceManager.GetString("Validation_SelectUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decimal separator currently set is not the period. It is recommended to adjust these settings beforehand to avoid entering values that do not correspond to those of the System..
        /// </summary>
        public static string Warning_DecimalSeparatorWarning {
            get {
                return ResourceManager.GetString("Warning_DecimalSeparatorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning_WarningLowercase {
            get {
                return ResourceManager.GetString("Warning_WarningLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Warning_WarningUppercase {
            get {
                return ResourceManager.GetString("Warning_WarningUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes_Camelcase {
            get {
                return ResourceManager.GetString("Yes_Camelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes_Lowercase {
            get {
                return ResourceManager.GetString("Yes_Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes_Uppercase {
            get {
                return ResourceManager.GetString("Yes_Uppercase", resourceCulture);
            }
        }
    }
}
