//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EllipseSAO900AddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("EllipseSAO900AddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ExportarCausaciones().
        /// </summary>
        internal static string RibbonEllipse_ExportarCausaciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ExportarCausaciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ExportarDatos().
        /// </summary>
        internal static string RibbonEllipse_ExportarDatos_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ExportarDatos_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ExportarDistribuciones().
        /// </summary>
        internal static string RibbonEllipse_ExportarDistribuciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ExportarDistribuciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ExportarReclasificaciones().
        /// </summary>
        internal static string RibbonEllipse_ExportarReclasificaciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ExportarReclasificaciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error FormatoCausaciones().
        /// </summary>
        internal static string RibbonEllipse_FormatoCausaciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_FormatoCausaciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error FormatoDistribuciones().
        /// </summary>
        internal static string RibbonEllipse_FormatoDistribuciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_FormatoDistribuciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error FormatoReclasificaciones().
        /// </summary>
        internal static string RibbonEllipse_FormatoReclasificaciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_FormatoReclasificaciones_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId no Existe o no tiene Acceso a Ellipse.
        /// </summary>
        internal static string RibbonEllipse_GetEmployeeName_DoesntExist {
            get {
                return ResourceManager.GetString("RibbonEllipse_GetEmployeeName_DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error GetEmployeeName().
        /// </summary>
        internal static string RibbonEllipse_GetEmployeeName_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_GetEmployeeName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuplierId no tiene Business Information en este distrito.
        /// </summary>
        internal static string RibbonEllipse_GetSupplierName_DoesntExist {
            get {
                return ResourceManager.GetString("RibbonEllipse_GetSupplierName_DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ValidarDatos().
        /// </summary>
        internal static string RibbonEllipse_ValidarDatos_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ValidarDatos_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ValidarReclasificaciones().
        /// </summary>
        internal static string RibbonEllipse_ValidarReclasificaciones_Error {
            get {
                return ResourceManager.GetString("RibbonEllipse_ValidarReclasificaciones_Error", resourceCulture);
            }
        }
    }
}
