//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsheetDatamodelLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LsdmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LsdmResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsheetDatamodelLibrary.LsdmResource", typeof(LsdmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Null.
        /// </summary>
        public static string Attribute_AllowNull {
            get {
                return ResourceManager.GetString("Attribute.AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string Attribute_DataType {
            get {
                return ResourceManager.GetString("Attribute.DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string Attribute_DefaultValue {
            get {
                return ResourceManager.GetString("Attribute.DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Attribute_Description {
            get {
                return ResourceManager.GetString("Attribute.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Attribute_Id {
            get {
                return ResourceManager.GetString("Attribute.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length.
        /// </summary>
        public static string Attribute_MaxLength {
            get {
                return ResourceManager.GetString("Attribute.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Precision.
        /// </summary>
        public static string Attribute_MaxPrecision {
            get {
                return ResourceManager.GetString("Attribute.MaxPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Scale.
        /// </summary>
        public static string Attribute_MaxScale {
            get {
                return ResourceManager.GetString("Attribute.MaxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Id.
        /// </summary>
        public static string Attribute_MeasureId {
            get {
                return ResourceManager.GetString("Attribute.MeasureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Id.
        /// </summary>
        public static string Attribute_ModelId {
            get {
                return ResourceManager.GetString("Attribute.ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheed Index.
        /// </summary>
        public static string Attribute_SheetIndex {
            get {
                return ResourceManager.GetString("Attribute.SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Attribute_Status {
            get {
                return ResourceManager.GetString("Attribute.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Id.
        /// </summary>
        public static string Attribute_ValidItemId {
            get {
                return ResourceManager.GetString("Attribute.ValidItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributesCamelcase {
            get {
                return ResourceManager.GetString("AttributesCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attributes.
        /// </summary>
        public static string AttributesLowercase {
            get {
                return ResourceManager.GetString("AttributesLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTRIBUTES.
        /// </summary>
        public static string AttributesUppercase {
            get {
                return ResourceManager.GetString("AttributesUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Datasheet_CreationDate {
            get {
                return ResourceManager.GetString("Datasheet.CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation User.
        /// </summary>
        public static string Datasheet_CreationUser {
            get {
                return ResourceManager.GetString("Datasheet.CreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Datasheet_Date {
            get {
                return ResourceManager.GetString("Datasheet.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Datasheet_Id {
            get {
                return ResourceManager.GetString("Datasheet.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Mod Date.
        /// </summary>
        public static string Datasheet_LastModDate {
            get {
                return ResourceManager.GetString("Datasheet.LastModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Mod User.
        /// </summary>
        public static string Datasheet_LastModUser {
            get {
                return ResourceManager.GetString("Datasheet.LastModUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Id.
        /// </summary>
        public static string Datasheet_ModelId {
            get {
                return ResourceManager.GetString("Datasheet.ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Id.
        /// </summary>
        public static string Datasheet_SequenceId {
            get {
                return ResourceManager.GetString("Datasheet.SequenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Datasheet_Shift {
            get {
                return ResourceManager.GetString("Datasheet.Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasheet.
        /// </summary>
        public static string DatasheetCamelcase {
            get {
                return ResourceManager.GetString("DatasheetCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datasheet.
        /// </summary>
        public static string DatasheetLowercase {
            get {
                return ResourceManager.GetString("DatasheetLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATASHEET.
        /// </summary>
        public static string DatasheetUppercase {
            get {
                return ResourceManager.GetString("DatasheetUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length value not required.
        /// </summary>
        public static string Error_Attribute_DatetimeValidation_LengthNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_DatetimeValidation_LengthNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision value not required.
        /// </summary>
        public static string Error_Attribute_DatetimeValidation_PrecisionNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_DatetimeValidation_PrecisionNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale values not required.
        /// </summary>
        public static string Error_Attribute_DatetimeValidation_ScaleNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_DatetimeValidation_ScaleNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length value not required. Use Precision (digits quantity) and Scale (decimal quantity of total digits) for Numeric types.
        /// </summary>
        public static string Error_Attribute_NumericValidation_LenghtNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_NumericValidation_LenghtNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale value can&apos;t be greater than Precision.
        /// </summary>
        public static string Error_Attribute_NumericValidation_ScaleGreaterThanPrecision {
            get {
                return ResourceManager.GetString("Error_Attribute_NumericValidation_ScaleGreaterThanPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text default value is limited in length.
        /// </summary>
        public static string Error_Attribute_TextValidation_DefaultValueWarning {
            get {
                return ResourceManager.GetString("Error_Attribute_TextValidation_DefaultValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length value not required.
        /// </summary>
        public static string Error_Attribute_TextValidation_LengthNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_TextValidation_LengthNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the length restriction.
        /// </summary>
        public static string Error_Attribute_VarcharValidation_LengthExceeded {
            get {
                return ResourceManager.GetString("Error_Attribute_VarcharValidation_LengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision value not required. Use Length for characters quantity.
        /// </summary>
        public static string Error_Attribute_VarcharValidation_PrecisionNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_VarcharValidation_PrecisionNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale values not required.
        /// </summary>
        public static string Error_Attribute_VarcharValidation_ScaleNotRequired {
            get {
                return ResourceManager.GetString("Error_Attribute_VarcharValidation_ScaleNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id required for datasheet.
        /// </summary>
        public static string Error_Datasheet_IdRequired {
            get {
                return ResourceManager.GetString("Error_Datasheet_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid datatype.
        /// </summary>
        public static string Error_DataType_Invalid {
            get {
                return ResourceManager.GetString("Error_DataType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id required for model.
        /// </summary>
        public static string Error_Model_IdRequired {
            get {
                return ResourceManager.GetString("Error_Model_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be null.
        /// </summary>
        public static string Error_ValueObject_NullValue {
            get {
                return ResourceManager.GetString("Error_ValueObject_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value can&apos;t be null.
        /// </summary>
        public static string Error_ValueObject_NumericValidation_NullValue {
            get {
                return ResourceManager.GetString("Error_ValueObject_NumericValidation_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the precision restriction.
        /// </summary>
        public static string Error_ValueObject_NumericValidation_Precision {
            get {
                return ResourceManager.GetString("Error_ValueObject_NumericValidation_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the scale restriction.
        /// </summary>
        public static string Error_ValueObject_NumericValidation_Scale {
            get {
                return ResourceManager.GetString("Error_ValueObject_NumericValidation_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_ValueObject_Varchar_L {
            get {
                return ResourceManager.GetString("Error_ValueObject_Varchar_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more updates couldn&apos;t be done. The transaction is rollbacked.
        /// </summary>
        public static string Exception_TransactionRollbacked {
            get {
                return ResourceManager.GetString("Exception.TransactionRollbacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Data Modeler.
        /// </summary>
        public static string LogsheetDatamodelerCamelcase {
            get {
                return ResourceManager.GetString("LogsheetDatamodelerCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGSHEET DATA MODELER.
        /// </summary>
        public static string LogsheetDatamodelerUppercase {
            get {
                return ResourceManager.GetString("LogsheetDatamodelerUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Measure_Code {
            get {
                return ResourceManager.GetString("Measure.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Measure_Description {
            get {
                return ResourceManager.GetString("Measure.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Measure_Id {
            get {
                return ResourceManager.GetString("Measure.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Measure_Name {
            get {
                return ResourceManager.GetString("Measure.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Measure_Status {
            get {
                return ResourceManager.GetString("Measure.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeId.
        /// </summary>
        public static string Measure_TypeId {
            get {
                return ResourceManager.GetString("Measure.TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Measure_Units {
            get {
                return ResourceManager.GetString("Measure.Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string MeasureCamelcase {
            get {
                return ResourceManager.GetString("MeasureCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measure.
        /// </summary>
        public static string MeasureLowercase {
            get {
                return ResourceManager.GetString("MeasureLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MeasureType_Description {
            get {
                return ResourceManager.GetString("MeasureType.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string MeasureType_Id {
            get {
                return ResourceManager.GetString("MeasureType.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Type.
        /// </summary>
        public static string MeasureTypeCamelcase {
            get {
                return ResourceManager.GetString("MeasureTypeCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measure type.
        /// </summary>
        public static string MeasureTypeLowercase {
            get {
                return ResourceManager.GetString("MeasureTypeLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEASURE TYPE.
        /// </summary>
        public static string MeasureTypeUppercase {
            get {
                return ResourceManager.GetString("MeasureTypeUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEASURE.
        /// </summary>
        public static string MeasureUppercase {
            get {
                return ResourceManager.GetString("MeasureUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Model_CreationDate {
            get {
                return ResourceManager.GetString("Model.CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation User.
        /// </summary>
        public static string Model_CreationUser {
            get {
                return ResourceManager.GetString("Model.CreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Model_Description {
            get {
                return ResourceManager.GetString("Model.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Model_Id {
            get {
                return ResourceManager.GetString("Model.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastMod Date.
        /// </summary>
        public static string Model_LastModDate {
            get {
                return ResourceManager.GetString("Model.LastModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastMod User.
        /// </summary>
        public static string Model_LastModUser {
            get {
                return ResourceManager.GetString("Model.LastModUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Model_Status {
            get {
                return ResourceManager.GetString("Model.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelCamelcase {
            get {
                return ResourceManager.GetString("ModelCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model.
        /// </summary>
        public static string ModelLowercase {
            get {
                return ResourceManager.GetString("ModelLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        public static string ModelUppercase {
            get {
                return ResourceManager.GetString("ModelUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Results_Failed {
            get {
                return ResourceManager.GetString("Results_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records were affected.
        /// </summary>
        public static string Results_NoRecordsAffected {
            get {
                return ResourceManager.GetString("Results_NoRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Results_Success {
            get {
                return ResourceManager.GetString("Results_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Results_Warning {
            get {
                return ResourceManager.GetString("Results_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Search_Date {
            get {
                return ResourceManager.GetString("Search.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string Search_FinishDate {
            get {
                return ResourceManager.GetString("Search.FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Search_Keyword {
            get {
                return ResourceManager.GetString("Search.Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Search_StartDate {
            get {
                return ResourceManager.GetString("Search.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ValidationItem_Description {
            get {
                return ResourceManager.GetString("ValidationItem.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinct Filter.
        /// </summary>
        public static string ValidationItem_DistincFilter {
            get {
                return ResourceManager.GetString("ValidationItem.DistincFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ValidationItem_Id {
            get {
                return ResourceManager.GetString("ValidationItem.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortable.
        /// </summary>
        public static string ValidationItem_Sortable {
            get {
                return ResourceManager.GetString("ValidationItem.Sortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Column.
        /// </summary>
        public static string ValidationItem_SourceColumn {
            get {
                return ResourceManager.GetString("ValidationItem.SourceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string ValidationItem_SourceName {
            get {
                return ResourceManager.GetString("ValidationItem.SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Table.
        /// </summary>
        public static string ValidationItem_SourceTable {
            get {
                return ResourceManager.GetString("ValidationItem.SourceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Items.
        /// </summary>
        public static string ValidationItemCamelcase {
            get {
                return ResourceManager.GetString("ValidationItemCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation items.
        /// </summary>
        public static string ValidationItemLowercase {
            get {
                return ResourceManager.GetString("ValidationItemLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATION ITEMS.
        /// </summary>
        public static string ValidationItemUppercase {
            get {
                return ResourceManager.GetString("ValidationItemUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Link.
        /// </summary>
        public static string ValidationSource_DbLink {
            get {
                return ResourceManager.GetString("ValidationSource.DbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Name.
        /// </summary>
        public static string ValidationSource_DbName {
            get {
                return ResourceManager.GetString("ValidationSource.DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Password.
        /// </summary>
        public static string ValidationSource_DbPassword {
            get {
                return ResourceManager.GetString("ValidationSource.DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Reference.
        /// </summary>
        public static string ValidationSource_DbReference {
            get {
                return ResourceManager.GetString("ValidationSource.DbReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db User.
        /// </summary>
        public static string ValidationSource_DbUser {
            get {
                return ResourceManager.GetString("ValidationSource.DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Type.
        /// </summary>
        public static string ValidationSource_EncodedPasswordType {
            get {
                return ResourceManager.GetString("ValidationSource.EncodedPasswordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ValidationSource_Name {
            get {
                return ResourceManager.GetString("ValidationSource.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Sources.
        /// </summary>
        public static string ValidationSourcesCamelcase {
            get {
                return ResourceManager.GetString("ValidationSourcesCamelcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation sources.
        /// </summary>
        public static string ValidationSourcesLowercase {
            get {
                return ResourceManager.GetString("ValidationSourcesLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATION SOURCES.
        /// </summary>
        public static string ValidationSourcesUppercase {
            get {
                return ResourceManager.GetString("ValidationSourcesUppercase", resourceCulture);
            }
        }
    }
}
